server:
  port: 10416

elasticsearch:
  scheme: http
  host: ${ES_HOST}
  port: 9200
  username: elastic
  password: ${ES_PASSWORD}
  index:
    book: trillion_books_dev_v2

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: project_be12_team1
    password: ${DB_PASSWORD}

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: ${REDIS_PW}
      database: 356

  #    Infra Setting
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false
    #    Infra Setting

# gemini-2.5-flash-live / gemini-2.5-flash-lite
gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: ${GEMINI_SEARCH_KEY}
  model: gemini-2.5-flash-lite
  timeout: 60s

pipeline:
  full-reindex:
    enabled: false

  review-summary:
    enabled: false            # 풀 리인덱스 동안은 false
    run-on-startup: false
    recent-review-limit: 50
    per-book-review-limit: 50
    cron: "0 30 2 * * *"

  book-stats:
    enabled: false             # 풀 리인덱스 동안은 false
    run-on-startup: false
    page-size: 2000
    ubq-chunk-size: 500
    cron: "0 40 2 * * *"

ai:
  ollama:
    base-url: ${OLLAMA_BASE_URL}
    embed-model: bge-m3
    timeout: 20s

  reranker:
    base-url: ${RERANKER_BASE_URL}
    timeout: 20s

  search:
    embedding-field: embeddingVector
    script-source: "cosineSimilarity(params.qv, '{field}') + 1.0"
    min-candidates: 50
    max-candidates: 200
    candidate-multiplier: 5
    rerank-text-max-len: 1200


