server:
  port: 10416

elasticsearch:
  scheme: http
  host: ${ES_HOST}
  port: 9200
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  index:
    book: ${ES_BOOK_INDEX:nhnacademy_books}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDRESS}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash-lite
  timeout: 30s

pipeline:
  review-summary:
    enabled: true
    run-on-startup: true
    recent-review-limit: 50
    per-book-review-limit: 50
    cron: "0 30 2 * * *"

  book-stats:
    enabled: true
    run-on-startup: true
    page-size: 2000
    ubq-chunk-size: 500
    cron: "0 40 2 * * *"

